// // languageList.ts
// // Flat dictionary of Qwen3-supported languages and their ISO codes

// export const qwen3Languages: Record<string, string> = {
//   English: "en",
//   French: "fr",
//   Portuguese: "pt",
//   German: "de",
//   Romanian: "ro",
//   Swedish: "sv",
//   Danish: "da",
//   Bulgarian: "bg",
//   Russian: "ru",
//   Czech: "cs",
//   Greek: "el",
//   Ukrainian: "uk",
//   Spanish: "es",
//   Dutch: "nl",
//   Slovak: "sk",
//   Croatian: "hr",
//   Polish: "pl",
//   Lithuanian: "lt",
//   Norwegian_Bokmal: "nb",
//   Norwegian_Nynorsk: "nn",
//   Persian: "fa",
//   Slovenian: "sl",
//   Gujarati: "gu",
//   Latvian: "lv",
//   Italian: "it",
//   Occitan: "oc",
//   Nepali: "ne",
//   Marathi: "mr",
//   Belarusian: "be",
//   Serbian: "sr",
//   Luxembourgish: "lb",
//   Venetian: "vec",
//   Assamese: "as",
//   Welsh: "cy",
//   Silesian: "szl",
//   Asturian: "ast",
//   Chhattisgarhi: "hne",
//   Awadhi: "awa",
//   Maithili: "mai",
//   Bhojpuri: "bho",
//   Sindhi: "sd",
//   Irish: "ga",
//   Faroese: "fo",
//   Hindi: "hi",
//   Punjabi: "pa",
//   Bengali: "bn",
//   Oriya: "or",
//   Tajik: "tg",
//   Eastern_Yiddish: "yi",
//   Lombard: "lmo",
//   Ligurian: "lij",
//   Sicilian: "scn",
//   Friulian: "fur",
//   Sardinian: "sc",
//   Galician: "gl",
//   Catalan: "ca",
//   Icelandic: "is",
//   Tosk_Albanian: "sq",
//   Limburgish: "li",
//   Dari: "prs",
//   Afrikaans: "af",
//   Macedonian: "mk",
//   Sinhala: "si",
//   Urdu: "ur",
//   Magahi: "mag",
//   Bosnian: "bs",
//   Armenian: "hy",
//   Chinese_Simplified: "zh",
//   Chinese_Traditional: "zh_tw",
//   Cantonese: "yue",
//   Burmese: "my",
//   Arabic_Standard: "ar",
//   Arabic_Najdi: "ars",
//   Arabic_Levantine: "apc",
//   Arabic_Egyptian: "arz",
//   Arabic_Moroccan: "ary",
//   Arabic_Mesopotamian: "acm",
//   Arabic_Taizzi_Adeni: "acq",
//   Arabic_Tunisian: "aeb",
//   Hebrew: "he",
//   Maltese: "mt",
//   Indonesian: "id",
//   Malay: "ms",
//   Tagalog: "tl",
//   Cebuano: "ceb",
//   Javanese: "jv",
//   Sundanese: "su",
//   Minangkabau: "min",
//   Balinese: "ban",
//   Banjar: "bjn",
//   Pangasinan: "pag",
//   Iloko: "ilo",
//   Waray: "war",
//   Tamil: "ta",
//   Telugu: "te",
//   Kannada: "kn",
//   Malayalam: "ml",
//   Turkish: "tr",
//   Northern_Azerbaijani: "az",
//   Northern_Uzbek: "uz",
//   Kazakh: "kk",
//   Bashkir: "ba",
//   Tatar: "tt",
//   Thai: "th",
//   Lao: "lo",
//   Finnish: "fi",
//   Estonian: "et",
//   Hungarian: "hu",
//   Vietnamese: "vi",
//   Khmer: "km",
//   Japanese: "ja",
//   Korean: "ko",
//   Georgian: "ka",
//   Basque: "eu",
//   Haitian_Creole: "ht",
//   Papiamento: "pap",
//   Kabuverdianu: "kea",
//   Tok_Pisin: "tpi",
//   Swahili: "sw",
// };

// export const languageArray = Object.entries(qwen3Languages); // [['English', 'en'], ...]

export const small100Languages: Record<string, string> = {
  Afrikaans: "af",
  Amharic: "am",
  Arabic: "ar",
  Asturian: "ast",
  Azerbaijani: "az",
  Bashkir: "ba",
  Belarusian: "be",
  Bulgarian: "bg",
  Bengali: "bn",
  Breton: "br",
  Bosnian: "bs",
  Catalan: "ca",
  Cebuano: "ceb",
  Czech: "cs",
  Welsh: "cy",
  Danish: "da",
  German: "de",
  Greek: "el",
  English: "en",
  Spanish: "es",
  Estonian: "et",
  Persian: "fa",
  Fulah: "ff",
  Finnish: "fi",
  French: "fr",
  Western_Frisian: "fy",
  Irish: "ga",
  Scottish_Gaelic: "gd",
  Galician: "gl",
  Gujarati: "gu",
  Hausa: "ha",
  Hebrew: "he",
  Hindi: "hi",
  Croatian: "hr",
  Haitian_Creole: "ht",
  Hungarian: "hu",
  Armenian: "hy",
  Indonesian: "id",
  Igbo: "ig",
  Iloko: "ilo",
  Icelandic: "is",
  Italian: "it",
  Japanese: "ja",
  Javanese: "jv",
  Georgian: "ka",
  Kazakh: "kk",
  Khmer: "km",
  Kannada: "kn",
  Korean: "ko",
  Luxembourgish: "lb",
  Ganda: "lg",
  Lingala: "ln",
  Lao: "lo",
  Lithuanian: "lt",
  Latvian: "lv",
  Malagasy: "mg",
  Macedonian: "mk",
  Malayalam: "ml",
  Mongolian: "mn",
  Marathi: "mr",
  Malay: "ms",
  Burmese: "my",
  Nepali: "ne",
  Dutch: "nl",
  Norwegian: "no",
  Northern_Sotho: "ns",
  Occitan: "oc",
  Oriya: "or",
  Punjabi: "pa",
  Polish: "pl",
  Pashto: "ps",
  Portuguese: "pt",
  Romanian: "ro",
  Russian: "ru",
  Sindhi: "sd",
  Sinhala: "si",
  Slovak: "sk",
  Slovenian: "sl",
  Somali: "so",
  Albanian: "sq",
  Serbian: "sr",
  Swati: "ss",
  Sundanese: "su",
  Swedish: "sv",
  Swahili: "sw",
  Tamil: "ta",
  Thai: "th",
  Tagalog: "tl",
  Tswana: "tn",
  Turkish: "tr",
  Ukrainian: "uk",
  Urdu: "ur",
  Uzbek: "uz",
  Vietnamese: "vi",
  Wolof: "wo",
  Xhosa: "xh",
  Yiddish: "yi",
  Yoruba: "yo",
  Chinese: "zh",
  Zulu: "zu",
};

export const languageArray = Object.entries(small100Languages);
